# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Distribute to Firebase"
  lane :firebase do
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "internal-testers",
      release_notes: ENV["VERSION"] || "Automated build",
      android_artifact_type: "APK",
      android_artifact_path: "androidApp/build/outputs/apk/release/androidApp-release.apk"
    )
  end

  desc "Upload AAB to Google Play (track from PLAY_TRACK env, default internal)"
  lane :play_upload do
    upload_to_play_store(
      track: ENV["PLAY_TRACK"] || "internal",
      json_key: "play-store.json",
      aab: "androidApp/build/outputs/bundle/release/androidApp-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
