package co.bleck.shammah.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light Scheme ───────────────────────────────────────────────────────────────
val PrimaryLight              = Color(0xFF5D4037)  // Warm Shammah Brown
val OnPrimaryLight            = Color(0xFFFFFFFF)
val PrimaryContainerLight     = Color(0xFFEBC760)  // Shammah Gold
val OnPrimaryContainerLight   = Color(0xFF3E2723)
val SecondaryLight            = Color(0xFFD4AF37)  // Deep Gold
val OnSecondaryLight          = Color(0xFF3E2723)
val SecondaryContainerLight   = Color(0xFFF5E9A9)
val OnSecondaryContainerLight = Color(0xFF3E2723)
val TertiaryLight             = Color(0xFF8D6E63)
val OnTertiaryLight           = Color(0xFFFFFFFF)
val TertiaryContainerLight    = Color(0xFFD7C2BB)
val OnTertiaryContainerLight  = Color(0xFF2C1A15)
val BackgroundLight           = Color(0xFFFFFBF0)
val OnBackgroundLight         = Color(0xFF1C1B1F)
val SurfaceLight              = Color(0xFFFFFFFF)
val OnSurfaceLight            = Color(0xFF1C1B1F)
val SurfaceVariantLight       = Color(0xFFF5EDD8)
val OnSurfaceVariantLight     = Color(0xFF6B5A4E)
val OutlineLight              = Color(0xFFB8A99A)
val OutlineVariantLight       = Color(0xFFDDD0C6)
val InverseSurfaceLight       = Color(0xFF322F2E)
val InverseOnSurfaceLight     = Color(0xFFF5EFED)
val SurfaceTintLight          = Color(0xFF5D4037)
val ErrorLight                = Color(0xFFB3261E)
val OnErrorLight              = Color(0xFFFFFFFF)
val ErrorContainerLight       = Color(0xFFF9DEDC)
val OnErrorContainerLight     = Color(0xFF410E0B)
val ScrimLight                = Color(0xFF000000)

// ── Dark Scheme ────────────────────────────────────────────────────────────────
val PrimaryDark               = Color(0xFFD7CCC8)
val OnPrimaryDark             = Color(0xFF3E2723)
val PrimaryContainerDark      = Color(0xFF5D4037)
val OnPrimaryContainerDark    = Color(0xFFD7CCC8)
val SecondaryDark             = Color(0xFFEBC760)
val OnSecondaryDark           = Color(0xFF3E2723)
val SecondaryContainerDark    = Color(0xFF6B5A00)
val OnSecondaryContainerDark  = Color(0xFFF5E9A9)
val TertiaryDark              = Color(0xFFBCAAA4)
val OnTertiaryDark            = Color(0xFF3E2723)
val TertiaryContainerDark     = Color(0xFF5D4037)
val OnTertiaryContainerDark   = Color(0xFFD7CCC8)
val BackgroundDark            = Color(0xFF1B1B1B)
val OnBackgroundDark          = Color(0xFFE6E1DC)
val SurfaceDark               = Color(0xFF2C2620)
val OnSurfaceDark             = Color(0xFFE6E1DC)
val SurfaceVariantDark        = Color(0xFF3D3530)
val OnSurfaceVariantDark      = Color(0xFFBCA89E)
val OutlineDark               = Color(0xFF7A6A61)
val OutlineVariantDark        = Color(0xFF4A3D38)
val InverseSurfaceDark        = Color(0xFFE6E1DC)
val InverseOnSurfaceDark      = Color(0xFF322F2E)
val SurfaceTintDark           = Color(0xFFD7CCC8)
val ErrorDark                 = Color(0xFFF2B8B5)
val OnErrorDark               = Color(0xFF601410)
val ErrorContainerDark        = Color(0xFF8C1D18)
val OnErrorContainerDark      = Color(0xFFF9DEDC)
val ScrimDark                 = Color(0xFF000000)