name: Android CI 

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > app/google-services.json

      - run: chmod +x gradlew

      - name: Diagnostics
        run: |
          java -version
          echo "VERSION=$VERSION"
          echo "VERSION_NAME=$VERSION_NAME"

      - name: Gradle version
        run: ./gradlew --version

      - run: ./gradlew test

      - run: ./gradlew lint

      - run: ./gradlew assembleRelease

      - name: Fetch tags
        run: git fetch --tags

      - name: Get tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: tag
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create Firebase credentials
        run: |
            echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase.json

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install gems
        run: bundle install

      - name: Fastlane Firebase
        if: startsWith(github.ref, 'refs/tags/v')
        run: fastlane firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: firebase.json